2023-09-15 00:59:03.512 | INFO     | __main__:<module>:19 - database connected successfully
2023-09-15 00:59:03.738 | ERROR    | bot.core.db.event_actions:get_event_by_day:26 - 'NoneType' object has no attribute 'to_dict'. Event in Суббота not found
Task exception was never retrieved
future: <Task finished name='Task-7' coro=<Dispatcher._process_polling_updates() done, defined at /root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=InvalidQueryID('Query is too old and response timeout expired or query id is invalid')>
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/root/SmokeDog/./bot/core/handlers/users.py", line 263, in choose_day
    await callback.answer("")
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/types/callback_query.py", line 57, in answer
    return await self.bot.answer_callback_query(callback_query_id=self.id,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 2890, in answer_callback_query
    return await self.request(api.Methods.ANSWER_CALLBACK_QUERY, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.InvalidQueryID: Query is too old and response timeout expired or query id is invalid
2023-09-15 00:59:19.679 | ERROR    | bot.core.db.event_actions:get_event_by_day:26 - 'NoneType' object has no attribute 'to_dict'. Event in Суббота not found
2023-09-15 00:59:21.158 | ERROR    | bot.core.db.event_actions:get_event_by_day:26 - 'NoneType' object has no attribute 'to_dict'. Event in Пятница not found
2023-09-15 00:59:59.057 | INFO     | __main__:<module>:19 - database connected successfully
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
2023-09-15 01:21:28.778 | INFO     | __main__:<module>:19 - database connected successfully
2023-09-15 13:12:23.778 | ERROR    | bot.core.db.client_actions:get_start_client_by_tg_id:55 - Client with telegram id = 412005372 was not found in DB
2023-09-15 13:12:23.779 | ERROR    | bot.core.handlers.users:start_command:53 - 'NoneType' object has no attribute 'phone_number'
2023-09-15 13:12:23.779 | INFO     | bot.core.handlers.users:start_command:54 - {'telegram_id': 412005372, 'name': 'Morozov', 'username': 'IamMoroz'} was added to database
2023-09-15 13:14:19.813 | ERROR    | bot.core.db.event_actions:get_event_by_day:26 - 'NoneType' object has no attribute 'to_dict'. Event in Пятница not found
2023-09-15 13:14:21.123 | ERROR    | bot.core.db.event_actions:get_event_by_day:26 - 'NoneType' object has no attribute 'to_dict'. Event in Суббота not found
2023-09-15 13:17:40.924 | ERROR    | bot.core.db.client_actions:get_start_client_by_tg_id:55 - Client with telegram id = 1519180471 was not found in DB
2023-09-15 13:17:40.925 | ERROR    | bot.core.handlers.users:start_command:53 - 'NoneType' object has no attribute 'phone_number'
2023-09-15 13:17:40.926 | INFO     | bot.core.handlers.users:start_command:54 - {'telegram_id': 1519180471, 'name': 'Крис', 'username': None} was added to database
2023-09-15 13:20:05.239 | ERROR    | bot.core.db.client_actions:get_start_client_by_tg_id:55 - Client with telegram id = 5662999549 was not found in DB
2023-09-15 13:20:05.239 | ERROR    | bot.core.handlers.users:start_command:53 - 'NoneType' object has no attribute 'phone_number'
2023-09-15 13:20:05.239 | INFO     | bot.core.handlers.users:start_command:54 - {'telegram_id': 5662999549, 'name': 'Smoke Dog Moscow', 'username': 'Smoke_Dog_Moscow'} was added to database
2023-09-15 13:21:06.619 | ERROR    | bot.core.db.client_actions:get_start_client_by_tg_id:55 - Client with telegram id = 813838729 was not found in DB
2023-09-15 13:21:06.620 | ERROR    | bot.core.handlers.users:start_command:53 - 'NoneType' object has no attribute 'phone_number'
2023-09-15 13:21:06.620 | INFO     | bot.core.handlers.users:start_command:54 - {'telegram_id': 813838729, 'name': 'Иван SD', 'username': None} was added to database
2023-09-15 13:22:52.920 | ERROR    | bot.core.db.event_actions:get_event_by_day:26 - 'NoneType' object has no attribute 'to_dict'. Event in Пятница not found
2023-09-15 13:22:54.751 | ERROR    | bot.core.db.event_actions:get_event_by_day:26 - 'NoneType' object has no attribute 'to_dict'. Event in Суббота not found
2023-09-15 13:23:22.892 | ERROR    | bot.core.db.event_actions:get_event_by_day:26 - 'NoneType' object has no attribute 'to_dict'. Event in Суббота not found
2023-09-15 13:23:23.083 | ERROR    | bot.core.db.event_actions:get_event_by_day:26 - 'NoneType' object has no attribute 'to_dict'. Event in Пятница not found
2023-09-15 13:23:25.310 | ERROR    | bot.core.db.event_actions:get_event_by_day:26 - 'NoneType' object has no attribute 'to_dict'. Event in Суббота not found
2023-09-15 13:23:26.842 | ERROR    | bot.core.db.event_actions:get_event_by_day:26 - 'NoneType' object has no attribute 'to_dict'. Event in Суббота not found
2023-09-15 13:26:47.207 | ERROR    | bot.core.db.event_actions:get_event_by_day:26 - 'NoneType' object has no attribute 'to_dict'. Event in Суббота not found
2023-09-15 13:28:39.520 | ERROR    | bot.core.db.event_actions:get_event_by_day:26 - 'NoneType' object has no attribute 'to_dict'. Event in Суббота not found
2023-09-15 13:29:13.315 | ERROR    | bot.core.db.event_actions:get_event_by_day:26 - 'NoneType' object has no attribute 'to_dict'. Event in Суббота not found
2023-09-15 13:34:57.116 | ERROR    | bot.core.db.client_actions:get_start_client_by_tg_id:55 - Client with telegram id = 1100606463 was not found in DB
2023-09-15 13:34:57.118 | ERROR    | bot.core.handlers.users:start_command:53 - 'NoneType' object has no attribute 'phone_number'
2023-09-15 13:34:57.118 | INFO     | bot.core.handlers.users:start_command:54 - {'telegram_id': 1100606463, 'name': 'Катика ✨️', 'username': 'gkatiica'} was added to database
2023-09-15 13:35:54.342 | ERROR    | bot.core.db.event_actions:get_event_by_day:26 - 'NoneType' object has no attribute 'to_dict'. Event in Пятница not found
2023-09-15 13:35:55.624 | ERROR    | bot.core.db.event_actions:get_event_by_day:26 - 'NoneType' object has no attribute 'to_dict'. Event in Суббота not found
2023-09-15 13:37:28.425 | ERROR    | bot.core.db.event_actions:get_event_by_day:26 - 'NoneType' object has no attribute 'to_dict'. Event in Пятница not found
2023-09-15 13:37:30.659 | ERROR    | bot.core.db.event_actions:get_event_by_day:26 - 'NoneType' object has no attribute 'to_dict'. Event in Суббота not found
2023-09-15 13:37:38.766 | ERROR    | bot.core.db.event_actions:get_event_by_day:26 - 'NoneType' object has no attribute 'to_dict'. Event in Пятница not found
2023-09-15 13:37:39.823 | ERROR    | bot.core.db.event_actions:get_event_by_day:26 - 'NoneType' object has no attribute 'to_dict'. Event in Суббота not found
Task exception was never retrieved
future: <Task finished name='Task-2600' coro=<Dispatcher._process_polling_updates() done, defined at /root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=KeyError('text')>
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/root/SmokeDog/./bot/core/handlers/admin.py", line 311, in enter_event_picture
    text = data["text"]
KeyError: 'text'
2023-09-15 13:45:18.677 | ERROR    | bot.core.db.event_actions:get_event_by_day:26 - 'NoneType' object has no attribute 'to_dict'. Event in Пятница not found
2023-09-15 13:52:09.605 | INFO     | __main__:<module>:19 - database connected successfully
2023-09-15 13:52:51.217 | INFO     | bot.core.handlers.admin:enter_event_picture:321 - [Errno 2] No such file or directory: 'sources/events/Суббота.jpeg'
/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/types/mixins.py:40: DeprecationWarning: destination parameter is deprecated, please use destination_dir or destination_file.
  warn_deprecated(
2023-09-15 13:53:06.392 | ERROR    | bot.core.db.event_actions:get_event_by_day:26 - 'NoneType' object has no attribute 'to_dict'. Event in Пятница not found
2023-09-15 18:20:58.438 | ERROR    | bot.core.db.client_actions:get_start_client_by_tg_id:55 - Client with telegram id = 5131083714 was not found in DB
2023-09-15 18:20:58.438 | ERROR    | bot.core.handlers.users:start_command:53 - 'NoneType' object has no attribute 'phone_number'
2023-09-15 18:20:58.439 | INFO     | bot.core.handlers.users:start_command:54 - {'telegram_id': 5131083714, 'name': 'Юлия', 'username': 'pohque'} was added to database
2023-09-16 20:08:45.202 | ERROR    | bot.core.db.event_actions:get_event_by_day:26 - 'NoneType' object has no attribute 'to_dict'. Event in Пятница not found
2023-09-17 04:57:49.649 | ERROR    | bot.core.db.client_actions:get_start_client_by_tg_id:55 - Client with telegram id = 5704760861 was not found in DB
2023-09-17 04:57:49.650 | ERROR    | bot.core.handlers.users:start_command:53 - 'NoneType' object has no attribute 'phone_number'
2023-09-17 04:57:49.650 | INFO     | bot.core.handlers.users:start_command:54 - {'telegram_id': 5704760861, 'name': 'Милена', 'username': 'gemiml'} was added to database
2023-09-17 10:16:23.522 | ERROR    | bot.core.db.event_actions:get_event_by_day:26 - 'NoneType' object has no attribute 'to_dict'. Event in Пятница not found
2023-09-17 16:35:03.925 | ERROR    | bot.core.db.event_actions:get_event_by_day:26 - 'NoneType' object has no attribute 'to_dict'. Event in Пятница not found
2023-09-18 13:45:50.502 | ERROR    | bot.core.db.event_actions:get_event_by_day:26 - 'NoneType' object has no attribute 'to_dict'. Event in Пятница not found
2023-09-18 16:02:42.412 | ERROR    | bot.core.db.client_actions:get_start_client_by_tg_id:55 - Client with telegram id = 5718160471 was not found in DB
2023-09-18 16:02:42.412 | ERROR    | bot.core.handlers.users:start_command:53 - 'NoneType' object has no attribute 'phone_number'
2023-09-18 16:02:42.412 | INFO     | bot.core.handlers.users:start_command:54 - {'telegram_id': 5718160471, 'name': 'Светлана', 'username': None} was added to database
2023-09-18 16:02:51.222 | ERROR    | bot.core.db.event_actions:get_event_by_day:26 - 'NoneType' object has no attribute 'to_dict'. Event in Пятница not found
2023-09-18 16:05:15.567 | ERROR    | bot.core.db.event_actions:get_event_by_day:26 - 'NoneType' object has no attribute 'to_dict'. Event in Пятница not found
2023-09-18 20:05:13.220 | ERROR    | bot.core.db.event_actions:get_event_by_day:26 - 'NoneType' object has no attribute 'to_dict'. Event in Пятница not found
2023-09-18 20:40:17.551 | ERROR    | bot.core.db.client_actions:get_start_client_by_tg_id:55 - Client with telegram id = 1103178722 was not found in DB
2023-09-18 20:40:17.551 | ERROR    | bot.core.handlers.users:start_command:53 - 'NoneType' object has no attribute 'phone_number'
2023-09-18 20:40:17.551 | INFO     | bot.core.handlers.users:start_command:54 - {'telegram_id': 1103178722, 'name': '095', 'username': None} was added to database
2023-09-19 02:28:51.206 | ERROR    | bot.core.db.event_actions:get_event_by_day:26 - 'NoneType' object has no attribute 'to_dict'. Event in Пятница not found
2023-09-19 19:05:05.236 | ERROR    | bot.core.db.event_actions:get_event_by_day:26 - 'NoneType' object has no attribute 'to_dict'. Event in Пятница not found
2023-09-19 19:40:04.581 | ERROR    | bot.core.db.client_actions:get_start_client_by_tg_id:55 - Client with telegram id = 534693055 was not found in DB
2023-09-19 19:40:04.582 | ERROR    | bot.core.handlers.users:start_command:53 - 'NoneType' object has no attribute 'phone_number'
2023-09-19 19:40:04.582 | INFO     | bot.core.handlers.users:start_command:54 - {'telegram_id': 534693055, 'name': 'Анна', 'username': 'annypov'} was added to database
2023-09-19 19:40:15.495 | ERROR    | bot.core.db.event_actions:get_event_by_day:26 - 'NoneType' object has no attribute 'to_dict'. Event in Пятница not found
2023-09-19 19:40:27.892 | ERROR    | bot.core.db.client_actions:get_start_client_by_tg_id:55 - Client with telegram id = 687522 was not found in DB
2023-09-19 19:40:27.893 | ERROR    | bot.core.handlers.users:start_command:53 - 'NoneType' object has no attribute 'phone_number'
2023-09-19 19:40:27.893 | INFO     | bot.core.handlers.users:start_command:54 - {'telegram_id': 687522, 'name': 'alovalova', 'username': 'alovalova'} was added to database
2023-09-19 19:42:43.180 | ERROR    | bot.core.db.client_actions:get_start_client_by_tg_id:55 - Client with telegram id = 295834848 was not found in DB
2023-09-19 19:42:43.181 | ERROR    | bot.core.handlers.users:start_command:53 - 'NoneType' object has no attribute 'phone_number'
2023-09-19 19:42:43.182 | INFO     | bot.core.handlers.users:start_command:54 - {'telegram_id': 295834848, 'name': '꧁Наталья', 'username': 'Elirya'} was added to database
2023-09-19 19:42:55.750 | ERROR    | bot.core.db.event_actions:get_event_by_day:26 - 'NoneType' object has no attribute 'to_dict'. Event in Пятница not found
2023-09-19 19:45:50.056 | ERROR    | bot.core.db.client_actions:get_start_client_by_tg_id:55 - Client with telegram id = 218681272 was not found in DB
2023-09-19 19:45:50.057 | ERROR    | bot.core.handlers.users:start_command:53 - 'NoneType' object has no attribute 'phone_number'
2023-09-19 19:45:50.057 | INFO     | bot.core.handlers.users:start_command:54 - {'telegram_id': 218681272, 'name': 'Айказ', 'username': None} was added to database
2023-09-19 19:47:33.263 | ERROR    | bot.core.db.event_actions:get_event_by_day:26 - 'NoneType' object has no attribute 'to_dict'. Event in Пятница not found
2023-09-19 19:58:37.053 | ERROR    | bot.core.db.client_actions:get_start_client_by_tg_id:55 - Client with telegram id = 520913788 was not found in DB
2023-09-19 19:58:37.054 | ERROR    | bot.core.handlers.users:start_command:53 - 'NoneType' object has no attribute 'phone_number'
2023-09-19 19:58:37.055 | INFO     | bot.core.handlers.users:start_command:54 - {'telegram_id': 520913788, 'name': 'Slava', 'username': 'Skvrts05'} was added to database
2023-09-19 20:01:25.638 | ERROR    | bot.core.db.client_actions:get_start_client_by_tg_id:55 - Client with telegram id = 247572438 was not found in DB
2023-09-19 20:01:25.638 | ERROR    | bot.core.handlers.users:start_command:53 - 'NoneType' object has no attribute 'phone_number'
2023-09-19 20:01:25.639 | INFO     | bot.core.handlers.users:start_command:54 - {'telegram_id': 247572438, 'name': 'Эльвира', 'username': 'bigulaeva'} was added to database
2023-09-19 20:02:24.363 | ERROR    | bot.core.db.client_actions:get_start_client_by_tg_id:55 - Client with telegram id = 682730225 was not found in DB
2023-09-19 20:02:24.364 | ERROR    | bot.core.handlers.users:start_command:53 - 'NoneType' object has no attribute 'phone_number'
2023-09-19 20:02:24.364 | INFO     | bot.core.handlers.users:start_command:54 - {'telegram_id': 682730225, 'name': '.', 'username': 'rostmos'} was added to database
2023-09-19 20:03:34.523 | ERROR    | bot.core.db.event_actions:get_event_by_day:26 - 'NoneType' object has no attribute 'to_dict'. Event in Пятница not found
2023-09-19 20:04:12.634 | ERROR    | bot.core.db.client_actions:get_start_client_by_tg_id:55 - Client with telegram id = 1063785322 was not found in DB
2023-09-19 20:04:12.640 | ERROR    | bot.core.handlers.users:start_command:53 - 'NoneType' object has no attribute 'phone_number'
2023-09-19 20:04:12.640 | INFO     | bot.core.handlers.users:start_command:54 - {'telegram_id': 1063785322, 'name': 'Александр', 'username': 'nnnnnnnaar'} was added to database
2023-09-19 20:13:26.882 | ERROR    | bot.core.db.client_actions:get_start_client_by_tg_id:55 - Client with telegram id = 419254422 was not found in DB
2023-09-19 20:13:26.883 | ERROR    | bot.core.handlers.users:start_command:53 - 'NoneType' object has no attribute 'phone_number'
2023-09-19 20:13:26.883 | INFO     | bot.core.handlers.users:start_command:54 - {'telegram_id': 419254422, 'name': 'Sandra', 'username': 'Sandrolog'} was added to database
2023-09-19 20:18:32.005 | ERROR    | bot.core.db.client_actions:get_start_client_by_tg_id:55 - Client with telegram id = 1914825915 was not found in DB
2023-09-19 20:18:32.008 | ERROR    | bot.core.handlers.users:start_command:53 - 'NoneType' object has no attribute 'phone_number'
2023-09-19 20:18:32.008 | INFO     | bot.core.handlers.users:start_command:54 - {'telegram_id': 1914825915, 'name': 'Евгений', 'username': 'Ddgoni'} was added to database
2023-09-19 20:20:59.769 | ERROR    | bot.core.db.client_actions:get_start_client_by_tg_id:55 - Client with telegram id = 284019482 was not found in DB
2023-09-19 20:20:59.770 | ERROR    | bot.core.handlers.users:start_command:53 - 'NoneType' object has no attribute 'phone_number'
2023-09-19 20:20:59.770 | INFO     | bot.core.handlers.users:start_command:54 - {'telegram_id': 284019482, 'name': 'Lera', 'username': 'iamfilatova'} was added to database
2023-09-19 20:23:04.921 | ERROR    | bot.core.db.client_actions:get_start_client_by_tg_id:55 - Client with telegram id = 429796408 was not found in DB
2023-09-19 20:23:04.922 | ERROR    | bot.core.handlers.users:start_command:53 - 'NoneType' object has no attribute 'phone_number'
2023-09-19 20:23:04.924 | INFO     | bot.core.handlers.users:start_command:54 - {'telegram_id': 429796408, 'name': 'Polina', 'username': 'ZkvPolina'} was added to database
2023-09-19 20:27:35.433 | ERROR    | bot.core.db.client_actions:get_start_client_by_tg_id:55 - Client with telegram id = 553103341 was not found in DB
2023-09-19 20:27:35.434 | ERROR    | bot.core.handlers.users:start_command:53 - 'NoneType' object has no attribute 'phone_number'
2023-09-19 20:27:35.434 | INFO     | bot.core.handlers.users:start_command:54 - {'telegram_id': 553103341, 'name': 'А', 'username': None} was added to database
2023-09-19 20:30:06.590 | ERROR    | bot.core.db.event_actions:get_event_by_day:26 - 'NoneType' object has no attribute 'to_dict'. Event in Пятница not found
2023-09-19 20:30:10.242 | ERROR    | bot.core.db.event_actions:get_event_by_day:26 - 'NoneType' object has no attribute 'to_dict'. Event in Пятница not found
2023-09-19 20:32:39.029 | ERROR    | bot.core.db.client_actions:get_start_client_by_tg_id:55 - Client with telegram id = 910388358 was not found in DB
2023-09-19 20:32:39.030 | ERROR    | bot.core.handlers.users:start_command:53 - 'NoneType' object has no attribute 'phone_number'
2023-09-19 20:32:39.030 | INFO     | bot.core.handlers.users:start_command:54 - {'telegram_id': 910388358, 'name': 'Вадим', 'username': 'neyshter'} was added to database
2023-09-19 20:59:48.887 | ERROR    | bot.core.db.client_actions:get_start_client_by_tg_id:55 - Client with telegram id = 521774772 was not found in DB
2023-09-19 20:59:48.888 | ERROR    | bot.core.handlers.users:start_command:53 - 'NoneType' object has no attribute 'phone_number'
2023-09-19 20:59:48.888 | INFO     | bot.core.handlers.users:start_command:54 - {'telegram_id': 521774772, 'name': 'Александр', 'username': None} was added to database
2023-09-19 21:56:17.189 | ERROR    | bot.core.db.client_actions:get_start_client_by_tg_id:55 - Client with telegram id = 772544285 was not found in DB
2023-09-19 21:56:17.189 | ERROR    | bot.core.handlers.users:start_command:53 - 'NoneType' object has no attribute 'phone_number'
2023-09-19 21:56:17.190 | INFO     | bot.core.handlers.users:start_command:54 - {'telegram_id': 772544285, 'name': 'Лиза', 'username': 'lizafanya'} was added to database
2023-09-19 22:06:06.654 | ERROR    | bot.core.db.client_actions:get_start_client_by_tg_id:55 - Client with telegram id = 775863039 was not found in DB
2023-09-19 22:06:06.655 | ERROR    | bot.core.handlers.users:start_command:53 - 'NoneType' object has no attribute 'phone_number'
2023-09-19 22:06:06.655 | INFO     | bot.core.handlers.users:start_command:54 - {'telegram_id': 775863039, 'name': 'Настюшка', 'username': 'stameskaa'} was added to database
2023-09-19 22:07:39.448 | ERROR    | bot.core.db.event_actions:get_event_by_day:26 - 'NoneType' object has no attribute 'to_dict'. Event in Пятница not found
2023-09-19 22:19:27.646 | ERROR    | bot.core.db.client_actions:get_start_client_by_tg_id:55 - Client with telegram id = 449179844 was not found in DB
2023-09-19 22:19:27.646 | ERROR    | bot.core.handlers.users:start_command:53 - 'NoneType' object has no attribute 'phone_number'
2023-09-19 22:19:27.646 | INFO     | bot.core.handlers.users:start_command:54 - {'telegram_id': 449179844, 'name': 'S', 'username': 'sv_kira'} was added to database
2023-09-19 22:22:20.299 | ERROR    | bot.core.db.client_actions:get_start_client_by_tg_id:55 - Client with telegram id = 880215692 was not found in DB
2023-09-19 22:22:20.300 | ERROR    | bot.core.handlers.users:start_command:53 - 'NoneType' object has no attribute 'phone_number'
2023-09-19 22:22:20.300 | INFO     | bot.core.handlers.users:start_command:54 - {'telegram_id': 880215692, 'name': 'ㅤ', 'username': 'no_n1xistent'} was added to database
2023-09-19 22:22:37.817 | ERROR    | bot.core.db.event_actions:get_event_by_day:26 - 'NoneType' object has no attribute 'to_dict'. Event in Пятница not found
2023-09-19 22:27:01.407 | ERROR    | bot.core.db.event_actions:get_event_by_day:26 - 'NoneType' object has no attribute 'to_dict'. Event in Пятница not found
2023-09-19 23:21:48.482 | ERROR    | bot.core.db.client_actions:get_start_client_by_tg_id:55 - Client with telegram id = 166876217 was not found in DB
2023-09-19 23:21:48.482 | ERROR    | bot.core.handlers.users:start_command:53 - 'NoneType' object has no attribute 'phone_number'
2023-09-19 23:21:48.483 | INFO     | bot.core.handlers.users:start_command:54 - {'telegram_id': 166876217, 'name': 'Евгений', 'username': None} was added to database
2023-09-19 23:36:22.695 | ERROR    | bot.core.db.client_actions:get_start_client_by_tg_id:55 - Client with telegram id = 527430304 was not found in DB
2023-09-19 23:36:22.695 | ERROR    | bot.core.handlers.users:start_command:53 - 'NoneType' object has no attribute 'phone_number'
2023-09-19 23:36:22.695 | INFO     | bot.core.handlers.users:start_command:54 - {'telegram_id': 527430304, 'name': 'Syavo4ka🥷🏽', 'username': 'Syav04ka'} was added to database
2023-09-20 09:19:10.415 | ERROR    | bot.core.db.event_actions:get_event_by_day:26 - 'NoneType' object has no attribute 'to_dict'. Event in Пятница not found
2023-09-20 11:00:44.819 | ERROR    | bot.core.db.client_actions:get_start_client_by_tg_id:55 - Client with telegram id = 6034588571 was not found in DB
2023-09-20 11:00:44.820 | ERROR    | bot.core.handlers.users:start_command:53 - 'NoneType' object has no attribute 'phone_number'
2023-09-20 11:00:44.820 | INFO     | bot.core.handlers.users:start_command:54 - {'telegram_id': 6034588571, 'name': 'А. Л. Ш.', 'username': 'luciyamom'} was added to database
2023-09-20 11:00:53.163 | ERROR    | bot.core.db.event_actions:get_event_by_day:26 - 'NoneType' object has no attribute 'to_dict'. Event in Пятница not found
2023-09-20 15:58:46.720 | ERROR    | bot.core.db.client_actions:get_start_client_by_tg_id:55 - Client with telegram id = 859271853 was not found in DB
2023-09-20 15:58:46.721 | ERROR    | bot.core.handlers.users:start_command:53 - 'NoneType' object has no attribute 'phone_number'
2023-09-20 15:58:46.721 | INFO     | bot.core.handlers.users:start_command:54 - {'telegram_id': 859271853, 'name': 'Алёна', 'username': 'al_bl_v'} was added to database
2023-09-20 16:19:26.036 | ERROR    | bot.core.db.event_actions:get_event_by_day:26 - 'NoneType' object has no attribute 'to_dict'. Event in Пятница not found
2023-09-20 17:18:36.556 | ERROR    | bot.core.db.client_actions:get_start_client_by_tg_id:55 - Client with telegram id = 1738706358 was not found in DB
2023-09-20 17:18:36.556 | ERROR    | bot.core.handlers.users:start_command:53 - 'NoneType' object has no attribute 'phone_number'
2023-09-20 17:18:36.557 | INFO     | bot.core.handlers.users:start_command:54 - {'telegram_id': 1738706358, 'name': 'Светлана', 'username': None} was added to database
2023-09-20 18:14:19.125 | ERROR    | bot.core.db.client_actions:get_start_client_by_tg_id:55 - Client with telegram id = 198017685 was not found in DB
2023-09-20 18:14:19.126 | ERROR    | bot.core.handlers.users:start_command:53 - 'NoneType' object has no attribute 'phone_number'
2023-09-20 18:14:19.126 | INFO     | bot.core.handlers.users:start_command:54 - {'telegram_id': 198017685, 'name': 'Svetlana T', 'username': 'sveta_tihomirova'} was added to database
2023-09-20 20:15:00.449 | ERROR    | bot.core.db.client_actions:get_start_client_by_tg_id:55 - Client with telegram id = 427960733 was not found in DB
2023-09-20 20:15:00.450 | ERROR    | bot.core.handlers.users:start_command:53 - 'NoneType' object has no attribute 'phone_number'
2023-09-20 20:15:00.450 | INFO     | bot.core.handlers.users:start_command:54 - {'telegram_id': 427960733, 'name': 'Tanya Biryuk', 'username': 'iamtabi'} was added to database
2023-09-20 22:04:26.681 | ERROR    | bot.core.db.client_actions:get_start_client_by_tg_id:55 - Client with telegram id = 360314232 was not found in DB
2023-09-20 22:04:26.681 | ERROR    | bot.core.handlers.users:start_command:53 - 'NoneType' object has no attribute 'phone_number'
2023-09-20 22:04:26.682 | INFO     | bot.core.handlers.users:start_command:54 - {'telegram_id': 360314232, 'name': 'natali', 'username': 'natalinatalievna'} was added to database
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 139, in make_request
    async with session.post(url, data=req, **kwargs) as response:
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiohttp/client.py", line 560, in _request
    await resp.start(conn)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 899, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 142, in make_request
    raise exceptions.NetworkError(f"aiohttp client throws an error: {e.__class__.__name__}: {e}")
aiogram.utils.exceptions.NetworkError: Aiohttp client throws an error: ClientOSError: [Errno 104] Connection reset by peer
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 128, in check_result
    raise exceptions.TelegramAPIError(description)
aiogram.utils.exceptions.TelegramAPIError: Bad Gateway
2023-09-21 16:44:55.342 | ERROR    | bot.core.db.event_actions:get_event_by_day:26 - 'NoneType' object has no attribute 'to_dict'. Event in Пятница not found
2023-09-21 16:59:53.289 | ERROR    | bot.core.db.client_actions:get_start_client_by_tg_id:55 - Client with telegram id = 1263948179 was not found in DB
2023-09-21 16:59:53.290 | ERROR    | bot.core.handlers.users:start_command:53 - 'NoneType' object has no attribute 'phone_number'
2023-09-21 16:59:53.290 | INFO     | bot.core.handlers.users:start_command:54 - {'telegram_id': 1263948179, 'name': 'Софья', 'username': 'SofyStep'} was added to database
2023-09-21 17:04:16.723 | INFO     | bot.core.handlers.admin:enter_event_picture:321 - [Errno 2] No such file or directory: 'sources/events/Суббота.mp4'
/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/types/mixins.py:40: DeprecationWarning: destination parameter is deprecated, please use destination_dir or destination_file.
  warn_deprecated(
2023-09-21 17:04:51.877 | INFO     | bot.core.handlers.admin:enter_event_picture:321 - [Errno 2] No such file or directory: 'sources/events/Пятница.jpeg'
/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/types/mixins.py:40: DeprecationWarning: destination parameter is deprecated, please use destination_dir or destination_file.
  warn_deprecated(
2023-09-21 22:26:47.332 | INFO     | __main__:<module>:19 - database connected successfully
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1056, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 507, in _sock_connect
    sock.connect(address)
OSError: [Errno 101] Network is unreachable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 139, in make_request
    async with session.post(url, data=req, **kwargs) as response:
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiohttp/connector.py", line 1209, in _create_direct_connection
    raise last_exc
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiohttp/connector.py", line 1178, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiohttp/connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [Network is unreachable]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 142, in make_request
    raise exceptions.NetworkError(f"aiohttp client throws an error: {e.__class__.__name__}: {e}")
aiogram.utils.exceptions.NetworkError: Aiohttp client throws an error: ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [Network is unreachable]
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1056, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 507, in _sock_connect
    sock.connect(address)
OSError: [Errno 101] Network is unreachable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 139, in make_request
    async with session.post(url, data=req, **kwargs) as response:
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiohttp/connector.py", line 1209, in _create_direct_connection
    raise last_exc
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiohttp/connector.py", line 1178, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiohttp/connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [Network is unreachable]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 142, in make_request
    raise exceptions.NetworkError(f"aiohttp client throws an error: {e.__class__.__name__}: {e}")
aiogram.utils.exceptions.NetworkError: Aiohttp client throws an error: ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [Network is unreachable]
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1056, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 507, in _sock_connect
    sock.connect(address)
OSError: [Errno 101] Network is unreachable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 139, in make_request
    async with session.post(url, data=req, **kwargs) as response:
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiohttp/connector.py", line 1209, in _create_direct_connection
    raise last_exc
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiohttp/connector.py", line 1178, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiohttp/connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [Network is unreachable]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 142, in make_request
    raise exceptions.NetworkError(f"aiohttp client throws an error: {e.__class__.__name__}: {e}")
aiogram.utils.exceptions.NetworkError: Aiohttp client throws an error: ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [Network is unreachable]
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1056, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 507, in _sock_connect
    sock.connect(address)
OSError: [Errno 101] Network is unreachable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 139, in make_request
    async with session.post(url, data=req, **kwargs) as response:
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiohttp/connector.py", line 1209, in _create_direct_connection
    raise last_exc
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiohttp/connector.py", line 1178, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiohttp/connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [Network is unreachable]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 142, in make_request
    raise exceptions.NetworkError(f"aiohttp client throws an error: {e.__class__.__name__}: {e}")
aiogram.utils.exceptions.NetworkError: Aiohttp client throws an error: ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [Network is unreachable]
Cause exception while getting updates.
Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 139, in make_request
    async with session.post(url, data=req, **kwargs) as response:
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiohttp/client.py", line 560, in _request
    await resp.start(conn)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 899, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/root/SmokeDog/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 142, in make_request
    raise exceptions.NetworkError(f"aiohttp client throws an error: {e.__class__.__name__}: {e}")
aiogram.utils.exceptions.NetworkError: Aiohttp client throws an error: ServerDisconnectedError: Server disconnected
2023-09-22 12:59:49.142 | ERROR    | bot.core.db.client_actions:get_start_client_by_tg_id:55 - Client with telegram id = 666182231 was not found in DB
2023-09-22 12:59:49.144 | ERROR    | bot.core.handlers.users:start_command:53 - 'NoneType' object has no attribute 'phone_number'
2023-09-22 12:59:49.144 | INFO     | bot.core.handlers.users:start_command:54 - {'telegram_id': 666182231, 'name': 'Гриша', 'username': 'Grishmanskiy'} was added to database
2023-09-22 13:48:06.395 | ERROR    | bot.core.db.client_actions:get_start_client_by_tg_id:55 - Client with telegram id = 646673176 was not found in DB
2023-09-22 13:48:06.397 | ERROR    | bot.core.handlers.users:start_command:53 - 'NoneType' object has no attribute 'phone_number'
2023-09-22 13:48:06.397 | INFO     | bot.core.handlers.users:start_command:54 - {'telegram_id': 646673176, 'name': 'Юлия', 'username': 'siberian_fox82'} was added to database
2023-09-22 14:05:13.905 | ERROR    | bot.core.db.client_actions:get_start_client_by_tg_id:55 - Client with telegram id = 1447632481 was not found in DB
2023-09-22 14:05:13.906 | ERROR    | bot.core.handlers.users:start_command:53 - 'NoneType' object has no attribute 'phone_number'
2023-09-22 14:05:13.907 | INFO     | bot.core.handlers.users:start_command:54 - {'telegram_id': 1447632481, 'name': 'Tony', 'username': 'TONYKAPLAN'} was added to database
2023-09-22 14:19:48.272 | ERROR    | bot.core.db.client_actions:get_start_client_by_tg_id:55 - Client with telegram id = 2040525420 was not found in DB
2023-09-22 14:19:48.274 | ERROR    | bot.core.handlers.users:start_command:53 - 'NoneType' object has no attribute 'phone_number'
2023-09-22 14:19:48.274 | INFO     | bot.core.handlers.users:start_command:54 - {'telegram_id': 2040525420, 'name': 'лисик🦊', 'username': None} was added to database
